site_name: Research docs
dev_addr: '0.0.0.0:8000'
theme:
  name: 'readthedocs'
nav:
- Home: index.md
- DevOps:
  - 'OpsCentric DevOps Course': 'devops/opscentric.md'
  - 'CI/CD':
    - 'Implementing a Full CI/CD Pipeline - Linux Academy': 'devops/cicd/fullcicdpipe.md'
  - 'Cloud':
    - 'Amazon Virtual Private Cloud (VPC)': 'devops/cloud/aws_vpc.md'
    - 'Azure Concepts - Linux Academy': 'devops/cloud/azureconcepts.md'
    - 'Google Cloud Essentials - Linux Academy': 'devops/cloud/gcpcessentials.md'
    - 'Intro: Network Service Mesh (NSM)': 'devops/cloud/servicemesh_intro.md'
    - 'Microsoft Azure Infrastructure and Deployment - Exam AZ-100 - Linux Academy': 'devops/cloud/azure_az100.md'
    - 'OpenStack Essentials - Linux Academy': 'devops/cloud/openstackessentials.md'
    - 'The Cloud Report 03/19': 'devops/cloud/cloudreport0319.md'
  - 'Conferences and Meetups':
    - 'Kubernights #1': 'devops/conferences/kubernights1.md'
    - 'SysOps/DevOps Polska':
      - "SysOps/DevOps Gdansk MeetUp #11": 'devops/conferences/sysopsdevops/sodo071119.md'
      - "SysOps/DevOps Gdansk MeetUp #12": 'devops/conferences/sysopsdevops/sodo160120.md'
  - Kubernetes:
    - 'Google Kubernetes Engine Deep Dive - Linux Academy': 'devops/kubernetes/gke-deepdive.md'
    - 'Kubernetes essentials - Linux Academy': 'devops/kubernetes/k8s-essentials.md'
    - 'Kubernetes Up and Running': 'devops/kubernetes/kuard.md'
    - 'Monitoring Kubernetes With Prometheus - Linux Academy': 'devops/kubernetes/kube-prom.md'
  - 'Vulnerability Scanning':
    - SonarQube:
      - '.NET Core scanning': 'devops/vulnerabilityscanning/sonarqube/dotnet.md'
- Networking:
  - 'Networking Foundations: Networking Basics - LinkedIn Learning': 'networking/networkfoundations.md'
  - 'Nginx Web Server Deep Dive - Linux Academy': 'networking/nginxdeepdive.md'
  - 'Practical Software-Defined Networking - LinkedIn Learning': 'networking/practicalsdn.md'
  - Random:
    - 'Game Theory - Coursera': 'random/gametheory.md'
  - Security:
    - 'Linux Foundation Cert Prep: Network Security - LinkedIn Learning': 'security/networksecurityprep.md'
    - 'OAuth and OpenID Connect': 'security/oauthoidc.md'
    - 'Conferences and Meetups':
      - 'Practical vulnerability detection methods in web applications - workshop': 'security/conferences/security_workshop_091119.md'
